[package]
name = "mothy_events"
version = "0.1.0"
edition = "2024"

[dependencies]
mothy_core = { version = "0.1.0", path = "../mothy_core" }
mothy_ansi = { path = "../mothy_ansi" }
serenity.workspace = true
tokio.workspace = true
